### ISSUE TITLE
Please 1.19.2 forge <3

### ISSUE THREAD

**Issue by kitovoi111** [Avalanche7CZ/ForgeAnnouncements#1]
Please 1.19.2 forge <3

**Comment by Avalanche7CZ** [comment]
Hello, I don't think the port is a problem. 
Which features are you most interested in? 
I also want to point out that 1.18.2 will always have the most new features and support, I'm on my own and don't have that much time.

**Comment by Avalanche7CZ** [comment]
@kitovoi111 it will be probably tonight.

**Comment by Avalanche7CZ** [comment]
@kitovoi111 Its done, but ofc its need testing and feedback.
https://github.com/Avalanche7CZ/ForgeAnnouncements/releases/tag/19.0.0b1

**Comment by kitovoi111** [comment]
thank you very much!!!
